"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.useUpdateUserSchemaStyles = void 0;
var tslib_1 = require("tslib");
var css_1 = require("@emotion/css");
var react_components_1 = require("@fluentui/react-components");
exports.useUpdateUserSchemaStyles = {
    container: (0, css_1.css)(templateObject_1 || (templateObject_1 = tslib_1.__makeTemplateObject(["\n    display: flex;\n    flex-direction: column;\n    gap: ", ";\n    padding: ", ";\n    background-color: ", ";\n    border-radius: ", ";\n    border: 1px solid ", ";\n    box-shadow: ", ";\n  "], ["\n    display: flex;\n    flex-direction: column;\n    gap: ", ";\n    padding: ", ";\n    background-color: ", ";\n    border-radius: ", ";\n    border: 1px solid ", ";\n    box-shadow: ", ";\n  "])), react_components_1.tokens.spacingVerticalM, react_components_1.tokens.spacingVerticalL, react_components_1.tokens.colorNeutralBackground1, react_components_1.tokens.borderRadiusMedium, react_components_1.tokens.colorNeutralStroke2, react_components_1.tokens.shadow4),
    header: (0, css_1.css)(templateObject_2 || (templateObject_2 = tslib_1.__makeTemplateObject(["\n    display: flex;\n    flex-direction: column;\n    gap: ", ";\n    margin-bottom: ", ";\n  "], ["\n    display: flex;\n    flex-direction: column;\n    gap: ", ";\n    margin-bottom: ", ";\n  "])), react_components_1.tokens.spacingVerticalS, react_components_1.tokens.spacingVerticalM),
    title: (0, css_1.css)(templateObject_3 || (templateObject_3 = tslib_1.__makeTemplateObject(["\n    font-size: ", ";\n    font-weight: ", ";\n    color: ", ";\n    margin: 0;\n  "], ["\n    font-size: ", ";\n    font-weight: ", ";\n    color: ", ";\n    margin: 0;\n  "])), react_components_1.tokens.fontSizeBase500, react_components_1.tokens.fontWeightSemibold, react_components_1.tokens.colorNeutralForeground1),
    subtitle: (0, css_1.css)(templateObject_4 || (templateObject_4 = tslib_1.__makeTemplateObject(["\n    font-size: ", ";\n    color: ", ";\n    margin: 0;\n  "], ["\n    font-size: ", ";\n    color: ", ";\n    margin: 0;\n  "])), react_components_1.tokens.fontSizeBase300, react_components_1.tokens.colorNeutralForeground2),
    form: (0, css_1.css)(templateObject_5 || (templateObject_5 = tslib_1.__makeTemplateObject(["\n    display: flex;\n    flex-direction: column;\n    gap: ", ";\n  "], ["\n    display: flex;\n    flex-direction: column;\n    gap: ", ";\n  "])), react_components_1.tokens.spacingVerticalL),
    userPickerSection: (0, css_1.css)(templateObject_6 || (templateObject_6 = tslib_1.__makeTemplateObject(["\n    display: flex;\n    flex-direction: column;\n    gap: ", ";\n  "], ["\n    display: flex;\n    flex-direction: column;\n    gap: ", ";\n  "])), react_components_1.tokens.spacingVerticalS),
    sectionGroup: (0, css_1.css)(templateObject_7 || (templateObject_7 = tslib_1.__makeTemplateObject(["\n    display: flex;\n    flex-direction: column;\n    gap: ", ";\n    padding: ", ";\n    background-color: ", ";\n    border-radius: ", ";\n    border: 1px solid ", ";\n  "], ["\n    display: flex;\n    flex-direction: column;\n    gap: ", ";\n    padding: ", ";\n    background-color: ", ";\n    border-radius: ", ";\n    border: 1px solid ", ";\n  "])), react_components_1.tokens.spacingVerticalM, react_components_1.tokens.spacingVerticalM, react_components_1.tokens.colorNeutralBackground2, react_components_1.tokens.borderRadiusMedium, react_components_1.tokens.colorNeutralStroke3),
    sectionTitle: (0, css_1.css)(templateObject_8 || (templateObject_8 = tslib_1.__makeTemplateObject(["\n    font-size: ", ";\n    font-weight: ", ";\n    color: ", ";\n    margin: 0;\n    margin-bottom: ", ";\n  "], ["\n    font-size: ", ";\n    font-weight: ", ";\n    color: ", ";\n    margin: 0;\n    margin-bottom: ", ";\n  "])), react_components_1.tokens.fontSizeBase400, react_components_1.tokens.fontWeightSemibold, react_components_1.tokens.colorNeutralForeground1, react_components_1.tokens.spacingVerticalS),
    inputRow: (0, css_1.css)(templateObject_9 || (templateObject_9 = tslib_1.__makeTemplateObject(["\n    display: flex;\n    flex-direction: column;\n    gap: ", ";\n  "], ["\n    display: flex;\n    flex-direction: column;\n    gap: ", ";\n  "])), react_components_1.tokens.spacingVerticalXS),
    inputGroup: (0, css_1.css)(templateObject_10 || (templateObject_10 = tslib_1.__makeTemplateObject(["\n    display: grid;\n    grid-template-columns: repeat(auto-fit, minmax(280px, 1fr));\n    gap: ", ";\n  "], ["\n    display: grid;\n    grid-template-columns: repeat(auto-fit, minmax(280px, 1fr));\n    gap: ", ";\n  "])), react_components_1.tokens.spacingHorizontalM),
    buttonGroup: (0, css_1.css)(templateObject_11 || (templateObject_11 = tslib_1.__makeTemplateObject(["\n    display: flex;\n    gap: ", ";\n    justify-content: flex-end;\n    margin-top: ", ";\n    padding-top: ", ";\n    border-top: 1px solid ", ";\n  "], ["\n    display: flex;\n    gap: ", ";\n    justify-content: flex-end;\n    margin-top: ", ";\n    padding-top: ", ";\n    border-top: 1px solid ", ";\n  "])), react_components_1.tokens.spacingHorizontalM, react_components_1.tokens.spacingVerticalL, react_components_1.tokens.spacingVerticalM, react_components_1.tokens.colorNeutralStroke3),
    loadingContainer: (0, css_1.css)(templateObject_12 || (templateObject_12 = tslib_1.__makeTemplateObject(["\n    display: flex;\n    align-items: center;\n    justify-content: center;\n    padding: ", ";\n    gap: ", ";\n  "], ["\n    display: flex;\n    align-items: center;\n    justify-content: center;\n    padding: ", ";\n    gap: ", ";\n  "])), react_components_1.tokens.spacingVerticalXXL, react_components_1.tokens.spacingHorizontalM),
    errorContainer: (0, css_1.css)(templateObject_13 || (templateObject_13 = tslib_1.__makeTemplateObject(["\n    padding: ", ";\n    background-color: ", ";\n    border: 1px solid ", ";\n    border-radius: ", ";\n    color: ", ";\n  "], ["\n    padding: ", ";\n    background-color: ", ";\n    border: 1px solid ", ";\n    border-radius: ", ";\n    color: ", ";\n  "])), react_components_1.tokens.spacingVerticalM, react_components_1.tokens.colorPaletteRedBackground1, react_components_1.tokens.colorPaletteRedBorder1, react_components_1.tokens.borderRadiusMedium, react_components_1.tokens.colorPaletteRedForeground1),
    successContainer: (0, css_1.css)(templateObject_14 || (templateObject_14 = tslib_1.__makeTemplateObject(["\n    padding: ", ";\n    background-color: ", ";\n    border: 1px solid ", ";\n    border-radius: ", ";\n    color: ", ";\n  "], ["\n    padding: ", ";\n    background-color: ", ";\n    border: 1px solid ", ";\n    border-radius: ", ";\n    color: ", ";\n  "])), react_components_1.tokens.spacingVerticalM, react_components_1.tokens.colorPaletteGreenBackground1, react_components_1.tokens.colorPaletteGreenBorder1, react_components_1.tokens.borderRadiusMedium, react_components_1.tokens.colorPaletteGreenForeground1),
    selectedUserCard: (0, css_1.css)(templateObject_15 || (templateObject_15 = tslib_1.__makeTemplateObject(["\n    padding: ", ";\n    background-color: ", ";\n    border-radius: ", ";\n    border: 1px solid ", ";\n    display: flex;\n    align-items: flex-start;\n    gap: ", ";\n  "], ["\n    padding: ", ";\n    background-color: ", ";\n    border-radius: ", ";\n    border: 1px solid ", ";\n    display: flex;\n    align-items: flex-start;\n    gap: ", ";\n  "])), react_components_1.tokens.spacingVerticalM, react_components_1.tokens.colorNeutralBackground3, react_components_1.tokens.borderRadiusMedium, react_components_1.tokens.colorNeutralStroke2, react_components_1.tokens.spacingHorizontalM),
    userInfo: (0, css_1.css)(templateObject_16 || (templateObject_16 = tslib_1.__makeTemplateObject(["\n    display: flex;\n    flex-direction: column;\n    gap: ", ";\n  "], ["\n    display: flex;\n    flex-direction: column;\n    gap: ", ";\n  "])), react_components_1.tokens.spacingVerticalXS),
    userName: (0, css_1.css)(templateObject_17 || (templateObject_17 = tslib_1.__makeTemplateObject(["\n    font-size: ", ";\n    font-weight: ", ";\n    color: ", ";\n  "], ["\n    font-size: ", ";\n    font-weight: ", ";\n    color: ", ";\n  "])), react_components_1.tokens.fontSizeBase400, react_components_1.tokens.fontWeightSemibold, react_components_1.tokens.colorNeutralForeground1),
    userEmail: (0, css_1.css)(templateObject_18 || (templateObject_18 = tslib_1.__makeTemplateObject(["\n    font-size: ", ";\n    color: ", ";\n  "], ["\n    font-size: ", ";\n    color: ", ";\n  "])), react_components_1.tokens.fontSizeBase300, react_components_1.tokens.colorNeutralForeground2),
};
var templateObject_1, templateObject_2, templateObject_3, templateObject_4, templateObject_5, templateObject_6, templateObject_7, templateObject_8, templateObject_9, templateObject_10, templateObject_11, templateObject_12, templateObject_13, templateObject_14, templateObject_15, templateObject_16, templateObject_17, templateObject_18;
//# sourceMappingURL=useUpdateUserSchemaStyles.js.map