"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ListViewSkeleton = void 0;
var tslib_1 = require("tslib");
var jsx_runtime_1 = require("@emotion/react/jsx-runtime");
var css_1 = require("@emotion/css");
var react_components_1 = require("@fluentui/react-components");
var ListViewSkeleton = function (_a) {
    var _b = _a.rows, rows = _b === void 0 ? 10 : _b, _c = _a.hasTeamsContext, hasTeamsContext = _c === void 0 ? false : _c;
    var windowHeight = window.innerHeight;
    var maxHeight = hasTeamsContext ? windowHeight - 250 : 700;
    var containerStyles = (0, css_1.css)(templateObject_1 || (templateObject_1 = tslib_1.__makeTemplateObject(["\n    display: flex;\n    flex-direction: column;\n    height: 100%;\n    min-height: ", "px;\n    padding: ", ";\n    border-radius: ", ";\n    background-color: ", ";\n    overflow: hidden;\n  "], ["\n    display: flex;\n    flex-direction: column;\n    height: 100%;\n    min-height: ", "px;\n    padding: ", ";\n    border-radius: ", ";\n    background-color: ", ";\n    overflow: hidden;\n  "])), maxHeight, react_components_1.tokens.spacingVerticalM, react_components_1.tokens.borderRadiusMedium, react_components_1.tokens.colorNeutralBackground1);
    var rowStyles = (0, css_1.css)(templateObject_2 || (templateObject_2 = tslib_1.__makeTemplateObject(["\n    display: grid;\n    grid-template-columns: 250px 200px 150px 130px 130px 100px;\n    gap: ", ";\n    padding: ", ";\n    border-bottom: 1px solid ", ";\n    align-items: center;\n    transition: all 0.2s ease-in-out;\n    border-radius: ", ";\n\n    &:hover {\n      background-color: ", ";\n    }\n\n    &:last-child {\n      border-bottom: none;\n    }\n\n    @media (max-width: 768px) {\n      grid-template-columns: 250px 200px;\n      gap: ", ";\n      padding: ", ";\n    }\n  "], ["\n    display: grid;\n    grid-template-columns: 250px 200px 150px 130px 130px 100px;\n    gap: ", ";\n    padding: ", ";\n    border-bottom: 1px solid ", ";\n    align-items: center;\n    transition: all 0.2s ease-in-out;\n    border-radius: ", ";\n\n    &:hover {\n      background-color: ", ";\n    }\n\n    &:last-child {\n      border-bottom: none;\n    }\n\n    @media (max-width: 768px) {\n      grid-template-columns: 250px 200px;\n      gap: ", ";\n      padding: ", ";\n    }\n  "])), react_components_1.tokens.spacingHorizontalM, react_components_1.tokens.spacingVerticalM, react_components_1.tokens.colorNeutralStroke3, react_components_1.tokens.borderRadiusSmall, react_components_1.tokens.colorNeutralBackground1Hover, react_components_1.tokens.spacingHorizontalS, react_components_1.tokens.spacingVerticalS);
    var avatarSkeletonStyles = (0, css_1.css)(templateObject_3 || (templateObject_3 = tslib_1.__makeTemplateObject(["\n    width: 32px;\n    height: 32px;\n    border-radius: 50%;\n    background: linear-gradient(90deg, \n      ", " 25%, \n      ", " 50%, \n      ", " 75%);\n    background-size: 200% 100%;\n    animation: shimmer 1.5s infinite;\n    margin-right: ", ";\n    box-shadow: ", ";\n\n    @keyframes shimmer {\n      0% { background-position: -200% 0; }\n      100% { background-position: 200% 0; }\n    }\n  "], ["\n    width: 32px;\n    height: 32px;\n    border-radius: 50%;\n    background: linear-gradient(90deg, \n      ", " 25%, \n      ", " 50%, \n      ", " 75%);\n    background-size: 200% 100%;\n    animation: shimmer 1.5s infinite;\n    margin-right: ", ";\n    box-shadow: ", ";\n\n    @keyframes shimmer {\n      0% { background-position: -200% 0; }\n      100% { background-position: 200% 0; }\n    }\n  "])), react_components_1.tokens.colorNeutralBackground3, react_components_1.tokens.colorSubtleBackground, react_components_1.tokens.colorNeutralBackground3, react_components_1.tokens.spacingHorizontalS, react_components_1.tokens.shadow2);
    var nameContainerStyles = (0, css_1.css)(templateObject_4 || (templateObject_4 = tslib_1.__makeTemplateObject(["\n    display: flex;\n    align-items: center;\n  "], ["\n    display: flex;\n    align-items: center;\n  "])));
    var textSkeletonStyles = (0, css_1.css)(templateObject_5 || (templateObject_5 = tslib_1.__makeTemplateObject(["\n    height: 16px;\n    background: linear-gradient(90deg, \n      ", " 25%, \n      ", " 50%, \n      ", " 75%);\n    background-size: 200% 100%;\n    animation: shimmer 1.5s infinite;\n    border-radius: ", ";\n    box-shadow: inset 0 1px 2px rgba(0, 0, 0, 0.05);\n\n    @keyframes shimmer {\n      0% { background-position: -200% 0; }\n      100% { background-position: 200% 0; }\n    }\n  "], ["\n    height: 16px;\n    background: linear-gradient(90deg, \n      ", " 25%, \n      ", " 50%, \n      ", " 75%);\n    background-size: 200% 100%;\n    animation: shimmer 1.5s infinite;\n    border-radius: ", ";\n    box-shadow: inset 0 1px 2px rgba(0, 0, 0, 0.05);\n\n    @keyframes shimmer {\n      0% { background-position: -200% 0; }\n      100% { background-position: 200% 0; }\n    }\n  "])), react_components_1.tokens.colorNeutralBackground3, react_components_1.tokens.colorSubtleBackground, react_components_1.tokens.colorNeutralBackground3, react_components_1.tokens.borderRadiusSmall);
    var shortTextStyles = (0, css_1.css)(templateObject_6 || (templateObject_6 = tslib_1.__makeTemplateObject(["\n    ", ";\n    width: 80%;\n  "], ["\n    ", ";\n    width: 80%;\n  "])), textSkeletonStyles);
    var mediumTextStyles = (0, css_1.css)(templateObject_7 || (templateObject_7 = tslib_1.__makeTemplateObject(["\n    ", ";\n    width: 60%;\n  "], ["\n    ", ";\n    width: 60%;\n  "])), textSkeletonStyles);
    var longTextStyles = (0, css_1.css)(templateObject_8 || (templateObject_8 = tslib_1.__makeTemplateObject(["\n    ", ";\n    width: 90%;\n  "], ["\n    ", ";\n    width: 90%;\n  "])), textSkeletonStyles);
    var nameTextStyles = (0, css_1.css)(templateObject_9 || (templateObject_9 = tslib_1.__makeTemplateObject(["\n    height: 16px;\n    background: linear-gradient(90deg, \n      ", " 25%, \n      ", " 50%, \n      ", " 75%);\n    background-size: 200% 100%;\n    animation: shimmer 1.5s infinite;\n    border-radius: ", ";\n    box-shadow: inset 0 1px 2px rgba(0, 0, 0, 0.05);\n    width: 140px;\n    flex-shrink: 0;\n\n    @keyframes shimmer {\n      0% { background-position: -200% 0; }\n      100% { background-position: 200% 0; }\n    }\n  "], ["\n    height: 16px;\n    background: linear-gradient(90deg, \n      ", " 25%, \n      ", " 50%, \n      ", " 75%);\n    background-size: 200% 100%;\n    animation: shimmer 1.5s infinite;\n    border-radius: ", ";\n    box-shadow: inset 0 1px 2px rgba(0, 0, 0, 0.05);\n    width: 140px;\n    flex-shrink: 0;\n\n    @keyframes shimmer {\n      0% { background-position: -200% 0; }\n      100% { background-position: 200% 0; }\n    }\n  "])), react_components_1.tokens.colorNeutralBackground3, react_components_1.tokens.colorSubtleBackground, react_components_1.tokens.colorNeutralBackground3, react_components_1.tokens.borderRadiusSmall);
    return ((0, jsx_runtime_1.jsx)("div", { className: containerStyles, children: Array.from({ length: rows }, function (_, index) { return ((0, jsx_runtime_1.jsxs)("div", { className: rowStyles, children: [(0, jsx_runtime_1.jsxs)("div", { className: nameContainerStyles, children: [(0, jsx_runtime_1.jsx)("div", { className: avatarSkeletonStyles }), (0, jsx_runtime_1.jsx)("div", { className: nameTextStyles })] }), (0, jsx_runtime_1.jsx)("div", { className: index % 3 === 0 ? longTextStyles : mediumTextStyles }), (0, jsx_runtime_1.jsx)("div", { className: index % 4 === 0 ? mediumTextStyles : shortTextStyles, css: (0, css_1.css)(templateObject_10 || (templateObject_10 = tslib_1.__makeTemplateObject(["\n              @media (max-width: 768px) {\n                display: none;\n              }\n            "], ["\n              @media (max-width: 768px) {\n                display: none;\n              }\n            "]))) }), (0, jsx_runtime_1.jsx)("div", { className: index % 2 === 0 ? mediumTextStyles : shortTextStyles, css: (0, css_1.css)(templateObject_11 || (templateObject_11 = tslib_1.__makeTemplateObject(["\n              @media (max-width: 768px) {\n                display: none;\n              }\n            "], ["\n              @media (max-width: 768px) {\n                display: none;\n              }\n            "]))) }), (0, jsx_runtime_1.jsx)("div", { className: index % 3 === 1 ? shortTextStyles : mediumTextStyles, css: (0, css_1.css)(templateObject_12 || (templateObject_12 = tslib_1.__makeTemplateObject(["\n              @media (max-width: 768px) {\n                display: none;\n              }\n            "], ["\n              @media (max-width: 768px) {\n                display: none;\n              }\n            "]))) }), (0, jsx_runtime_1.jsx)("div", { className: index % 5 === 0 ? shortTextStyles : (0, css_1.css)(templateObject_13 || (templateObject_13 = tslib_1.__makeTemplateObject(["height: 20px; width: 50px; ", "; border-radius: 12px;"], ["height: 20px; width: 50px; ", "; border-radius: 12px;"])), textSkeletonStyles), css: (0, css_1.css)(templateObject_14 || (templateObject_14 = tslib_1.__makeTemplateObject(["\n              @media (max-width: 768px) {\n                display: none;\n              }\n            "], ["\n              @media (max-width: 768px) {\n                display: none;\n              }\n            "]))) })] }, index)); }) }));
};
exports.ListViewSkeleton = ListViewSkeleton;
var templateObject_1, templateObject_2, templateObject_3, templateObject_4, templateObject_5, templateObject_6, templateObject_7, templateObject_8, templateObject_9, templateObject_10, templateObject_11, templateObject_12, templateObject_13, templateObject_14;
//# sourceMappingURL=ListViewSkeleton.js.map